# -*- coding: utf-8 -*-
"""enhanced-superstore-sales analysis

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GL43KmwVzD25ah9558EKyBTmAo6iVL1e
"""

import os
os.environ['KAGGLE_USERNAME']='anjali'
os.environ['KAGGLE_KEY']='KGAT_23723e87be0c67988194abd2d432f79d'

!pip install kaggle

!kaggle datasets download -d 'sumeakash/enhanced-superstore-sales-dataset'

!unzip /content/enhanced-superstore-sales-dataset.zip -d /content/anjalienhanced-superstore-sales

import pandas as pd
df = pd.read_csv("/content/enhanced-superstore-sales-dataset.zip")
df.head(10)

df.tail(10)

print(len(df))

print(df.shape)

df.info()

df.describe()

df.duplicated().sum()

df.dtypes

print(df.columns)

print(df['Sales'])

df.drop('Shipping Cost', axis=1, inplace=True)
print(df)

print(df['Discount'].mean())

df.isnull().sum()

df['Discount'] = df['Discount'].fillna(df['Discount'].median())

df['Discount'].head(10)

df.drop_duplicates(inplace=True)
print(df)

df.isnull().sum()

import matplotlib.pyplot as plt

df['Category'].value_counts().plot(kind='bar')
plt.title("Category Distribution")
plt.show()

df['High_Sales'] = (df['Sales'] > df['Sales'].median()).astype(int)

X = df[['Discount']]   # you can add more columns later
y = df['High_Sales']

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

from sklearn.linear_model import LogisticRegression

model = LogisticRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test, y_pred)
print(f"Accuracy: {accuracy:.4f}")